name: Docker Build and Push

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up the matrix
        id: set-matrix
        run: |
          versions=$(find php-apache php-fpm -type f -name '*.Dockerfile' | sed -e 's|php-apache/||' -e 's|php-fpm/||' -e 's|.Dockerfile||' | tr '\n' ',')
          versions="${versions%,}" # Remove the trailing comma
          echo "matrix={\"version\":[\"${versions//,/\",\"}\"]}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: changes
    if: ${{ needs.changes.outputs.matrix != '{"version":[]}' }}
    runs-on: [ubuntu-latest, macos-latest]
    concurrency:
      group: docker-build-${{ github.workflow }}-${{ github.event_name }}-${{ github.run_id }}
      cancel-in-progress: false
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.matrix) }}
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Docker tag and file
        id: prepare
        run: |
          VERSION="${{ matrix.version }}"
          if [ -z "$VERSION" ]; then
            echo "Error: Version is empty"
            exit 1
          fi

          DOCKER_TAG="${VERSION//_/.}"
          if [[ "$VERSION" == *"alpine"* ]]; then
            DOCKERFILE="php-fpm/${DOCKER_TAG%-alpine}-alpine.Dockerfile"
            IMAGE_NAME="ejklock/php-fpm-alpine:${DOCKER_TAG%-alpine}"
          elif [[ "$VERSION" == "php_fpm" ]]; then
            DOCKERFILE="php-fpm/Dockerfile"
            IMAGE_NAME="ejklock/php-fpm:latest"
          elif [[ "$VERSION" == "php_apache" ]]; then
            DOCKERFILE="php-apache/Dockerfile"
            IMAGE_NAME="ejklock/php-apache:latest"
          else
            DOCKERFILE="php-fpm/${DOCKER_TAG}.Dockerfile"
            IMAGE_NAME="ejklock/php-fpm:${DOCKER_TAG}"
          fi

          if [ ! -f "$DOCKERFILE" ]; then
            echo "Error: Dockerfile not found: $DOCKERFILE"
            exit 1
          fi

          echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ contains(steps.prepare.outputs.dockerfile, 'php-apache') && './php-apache' || './php-fpm' }}
          file: ${{ steps.prepare.outputs.dockerfile }}
          push: true
          tags: ${{ steps.prepare.outputs.image_name }}
        continue-on-error: true
