name: Release
on:
  push:
    branches: [php-fpm]
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Rodar WorkFlow Manualmente'
        required: true
        default: 'warning'
      tags:
        description: 'Insira a TAG para o cenário'
env:
  VERSION_FILE: ./.env
  VERSION_EXTRACT_PATTERN: '(?<=NEXT_PUBLIC_VERSION=).+'

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Generate version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: ${{env.VERSION_FILE}}
          version-file-extraction-pattern: ${{env.VERSION_EXTRACT_PATTERN}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Api do Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: 'ejklock/php-fpm:${{env.TAG_NAME}}'
       
